#name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pyarrow=2.0
  - fastparquet=0.7.1
  - pip:
      - wandb==0.12.1
      